baseProfile: qodana.recommended

inspections:
  - inspection: ConstantOnWrongSideOfComparison
    myConstantShouldGoLeft: false

groups:
  - groupId: Java
    inspections:
      - InstanceofThis
      - InstanceofChain
      - ClassReferencesSubclass
      - DeclareCollectionAsInterface
      - FeatureEnvy
      - OverlyStrongTypeCast
      - TypeMayBeWeakened
      - UnresolvedClassReferenceRepair
      - AssignmentToNull
      - ReplaceAssignmentWithOperatorAssignment
      - AssignmentToCatchBlockParameter
      - AssignmentToForLoopParameter
      - AssignmentToLambdaParameter
      - AssignmentToMethodParameter
      - AssignmentToStaticFieldFromInstanceMethod
      - AssignmentUsedAsCondition
      - AssignmentToSuperclassField
      - NestedAssignment
      - IncrementDecrementUsedAsExpression
      - DoubleLiteralMayBeFloatLiteral
      - IntLiteralMayBeLongLiteral
      - CastThatLosesPrecision
      - UnnecessaryExplicitNumericCast
      - ClassNamePrefixedWithPackageName
      - ClassNameSameAsAncestorName
      - ExceptionNameDoesntEndWithException
      - NonExceptionNameEndsWithException
      - AnonymousClassMethodCount
      - ClassNestingDepth
      - AnonymousClassComplexity
      - ClassMayBeInterface
      - ListenerMayUseAdapter
      - ClassNameDiffersFromFileName
      - ClassWithOnlyPrivateConstructors
      - FieldCanBeLocal
      - InnerClassOnInterface
      - MarkerInterface
      - MethodReturnAlwaysConstant
      - MultipleTopLevelClassesInFile
      - NoopMethodInAbstractClass
      - NonFinalFieldInEnum
      - ClassInitializer
      - EmptyClass
      - NonFinalUtilityClass
      - UtilityClassWithPublicConstructor
      - UtilityClassWithoutPrivateConstructor
      - ParameterCanBeLocal
      - CloneInNonCloneableClass
      - CloneCallsConstructors
      - NonPublicClone
      - CloneReturnsClassType
      - FileEqualsUsage
      - ThrowablePrintedToSystemOut
      - ThrowablePrintStackTrace
      - ThreadDumpStack
      - CommentedOutCode
      - Deprecation
      - DeprecatedIsStillUsed
      - ExtractMethodRecommender
      - OptionalAssignedToNull
      - RedundantScheduledForRemovalAnnotation
      - MarkedForRemoval
      - SystemOutErr
      - ObsoleteCollection
      - UseOfObsoleteDateTimeApi
      - AssertMessageNotString
      - EqualsCalledOnEnumConstant
      - SimplifiableIfStatement
      - ListIndexOfReplaceableByContains
      - ObjectsEqualsCanBeSimplified
      - OptionalContainsCollection
      - ReturnSeparatedFromComputation
      - SizeReplaceableByIsEmpty
      - ArrayCanBeReplacedWithEnumValues
      - ArrayCreationWithoutNewKeyword
      - JoinDeclarationAndAssignmentJava
      - BlockMarkerComments
      - CStyleArrayDeclaration
      - CallToStringConcatCanBeReplacedByOperator
      - BoundedWildcard
      - ChainedEquality
      - ExtendsObject
      - ConditionalCanBeOptional
      - ConfusingOctalEscape
      - ConstantExpression
      - ConstantOnWrongSideOfComparison
      - ControlFlowStatementWithoutBraces
      - MoveFieldAssignmentToInitializer
      - FieldMayBeFinal
      - RedundantLabeledSwitchRuleCodeBlock
      - MissortedModifiers
      - MultipleVariablesInDeclaration
      - OptionalIsPresent
      - EscapedSpace
      - ReassignedVariable
      - UnnecessaryConstructor
      - FillPermitsList
      - SimplifiableAnnotation
      - CharsetObjectCanBeUsed
      - FuseStreamOperations
      - TrailingWhitespacesInTextBlock
      - TypeParameterExtendsObject
      - UnnecessarilyQualifiedStaticallyImportedElement
      - UnnecessaryFinalOnLocalVariableOrParameter
      - SimplifiableEqualsExpression
      - UnnecessarySuperQualifier
      - UnnecessaryThis
      - UnnecessaryToStringCall
      - UnnecessaryBlockStatement
      - UnnecessaryCallToStringValueOf
      - UnnecessaryFullyQualifiedName
      - UnnecessaryModifier
      - UnnecessaryQualifierForThis
      - UnnecessarySemicolon
      - UnqualifiedInnerClassAccess
      - UNCHECKED_WARNING
      - DefaultNotLastCaseInSwitch
      - ForLoopReplaceableByWhile
      - NegatedIfElse
      - IfStatementWithTooManyBranches
      - BooleanExpressionMayBeConditional
      - SwitchExpressionCanBePushedDown
      - ConditionalBreakInInfiniteLoop
      - ConditionalCanBePushedInsideExpression
      - NegatedConditional
      - EnumSwitchStatementWhichMissesCases
      - ExpressionMayBeFactorized
      - FallthruInSwitchStatement
      - LabeledStatement
      - GroovyLoopStatementThatDoesntLoop
      - LoopWithImplicitTerminationCondition
      - SwitchStatementWithTooManyBranches
      - NegatedConditionalExpression
      - NegatedEqualityExpression
      - NestedSwitchStatement
      - NestedConditionalExpression
      - OverlyComplexBooleanExpression
      - PointlessIndexOfComparison
      - ConfusingElse
      - TrivialIf
      - IfCanBeAssertion
      - BooleanVariableAlwaysNegated
      - NegativelyNamedBooleanVariable
      - UnnecessaryLocalVariable
      - ReuseOfLocalVariable
      - TooBroadScope
      - FinalMethodInFinalClass
      - ProtectedMemberInFinalClass
      - AccessStaticViaInstance
      - WeakerAccess
      - CanBeFinal
      - DuplicateThrows
      - EmptyInitializer
      - EmptyMethod
      - FunctionalExpressionCanBeFolded
      - SameReturnValue
      - UnusedReturnValue
      - SameParameterValue
      - RedundantExplicitClose
      - RedundantThrows
      - RedundantLambdaParameterType
      - RedundantRecordConstructor
      - TrivialFunctionalExpressionUsage
      - UnnecessaryModuleDependencyInspection
      - unused
      - UnusedLabel
      - UnusedLibrary
      - SillyAssignment
      - FabricModJsonEntrypointsValidation
      - UnresolvedFabricModJsonReference
      - Finalize
      - Annotator
      - DuplicatedCode
      - EmptyDirectory
      - InconsistentLineSeparators
      - InjectedReferences
      - IncorrectFormatting
      - JavaAnnotator
      - ProblematicWhitespace
      - RedundantSuppression
      - TodoComment
      - JavaLangImport
      - SamePackageImport
      - UNUSED_IMPORT
      - AbstractClassNeverImplemented
      - AbstractClassWithoutAbstractMethods
      - AbstractMethodOverridesAbstractMethod
      - AbstractMethodWithMissingImplementations
      - ExtendsConcreteCollection
      - ExtendsUtilityClass
      - FrequentlyUsedInheritorInspection
      - RedundantMethodOverride
      - MissingOverrideAnnotation
      - ProblematicVarargsMethodOverride
      - YAMLSchemaDeprecation
      - YAMLDuplicatedKeys
      - YAMLRecursiveAlias
      - YAMLIncompatibleTypes
      - YAMLUnresolvedAlias
      - YAMLUnusedAnchor
      - YAMLSchemaValidation
      - UseOfAnotherObjectsPrivateField
      - AssignmentOrReturnOfFieldWithMutableType
      - GroovyContinueOrBreakFromFinallyBlock
      - ErrorRethrown
      - InstanceofCatchParameter
      - NullThrown
      - ThreadDeathRethrown
      - ThrowCaughtLocally
      - ExceptionFromCatchWhichDoesntWrap
      - ExtendsThrowable
      - NewExceptionWithoutArguments
      - NestedTryStatement
      - NonFinalFieldOfException
      - TooBroadCatch
      - TooBroadThrows
      - BadExceptionCaught
      - BadExceptionDeclared
      - BadExceptionThrown
      - UncheckedExceptionClass
      - ThrowsRuntimeException
      - TypeParameterExtendsFinalClass
      - StaticInheritance
      - RedundantImplements
      - NonProtectedConstructorInAbstractClass
      - ParameterTypePreventsOverriding
      - ThisEscapedInConstructor
      - DoubleBraceInitialization
      - InstanceVariableInitialization
      - InstanceVariableUninitializedUse
      - NonFinalStaticVariableUsedInClassInitialization
      - StaticVariableInitialization
      - StaticVariableUninitializedUse
      - NonThreadSafeLazyInitialization
      - ReadWriteStringCanBeUsed
      - StringRepeatCanBeUsed
      - VariableTypeCanBeExplicit
      - Java9CollectionFactory
      - ReplaceNullCheck
      - Java8ListSort
      - ComparatorCombinators
      - Convert2Lambda
      - Anonymous2MethodRef
      - AnonymousHasLambdaAlternative
      - FoldExpressionIntoStream
      - LambdaCanBeMethodCall
      - Convert2MethodRef
      - Convert2streamapi
      - Java8CollectionRemoveIf
      - Java8ListReplaceAll
      - Java8MapForEach
      - Java8MapApi
      - SimplifyForEach
      - CodeBlock2Expr
      - EqualsReplaceableByObjectsCall
      - TryFinallyCanBeTryWithResources
      - Convert2Diamond
      - TryWithIdenticalCatches
      - SafeVarargsDetector
      - BigDecimalLegacyMethod
      - ForCanBeForeach
      - IndexOfReplaceableByContains
      - StringBufferReplaceableByStringBuilder
      - WhileCanBeForeach
      - MethodCanBeVariableArityMethod
      - RawUseOfParameterizedType
      - CollectionsFieldAccessReplaceableByMethodCall
      - UnnecessaryBoxing
      - UnnecessaryUnboxing
      - UseCompareMethod
      - IfCanBeSwitch
      - EnumerationCanBeIteration
      - HtmlTagCanBeJavadocTag
      - PackageInfoWithoutPackage
      - PackageDotHtmlMayBePackageInfo
      - JavadocBlankLines
      - ReplaceWithJavadoc
      - DanglingJavadoc
      - JavadocReference
      - JavadocHtmlLint
      - JavadocDeclaration
      - JavadocLinkAsPlainText
      - MismatchedJavadocCode
      - MissingDeprecatedAnnotation
      - UnnecessaryInheritDoc
      - UnnecessaryJavaDocLink
      - JsonSchemaCompliance
      - JsonStandardCompliance
      - Json5StandardCompliance
      - JsonSchemaDeprecation
      - MongoDBJsonDuplicatePropertyKeys
      - JsonDuplicatePropertyKeys
      - JsonSchemaRefReference
      - InjectionNotApplicable
      - LanguageMismatch
      - UnknownLanguage
      - ClassWithMultipleLoggers
      - LoggingConditionDisagreesWithLogLevelStatement
      - LoggerInitializedWithForeignClass
      - NonStaticFinalLogger
      - StringConcatenationArgumentToLogCall
      - MarkdownIncorrectTableFormatting
      - MarkdownIncorrectlyNumberedListItem
      - MarkdownLinkDestinationWithSpaces
      - MarkdownOutdatedTableOfContents
      - MarkdownNoTableBorders
      - MarkdownUnresolvedFileReference
      - MarkdownUnresolvedHeaderReference
      - MarkdownUnresolvedLinkLabel
      - SystemGC
      - ReturnOfInnerClass
      - ZeroLengthArrayInitialization
      - BooleanMethodNameMustStartWithQuestion
      - LambdaUnfriendlyMethodOverload
      - MethodNameSameAsClassName
      - MethodNameSameAsParentName
      - MisspelledMethodName
      - NonBooleanMethodNameMayNotStartWithQuestion
      - OverloadedVarargsMethod
      - ThreeNegationsPerMethod
      - ThrownExceptionsPerMethod
      - WrongEntityDataParameterClass
      - MissingFormat
      - NoTranslation
      - SuperfluousFormat
      - IsCancelled
      - InjectCouldBeOverwrite
      - InjectIntoConstructor
      - InterfaceIsInterface
      - ShadowFieldPrefix
      - AmbiguousMixinReference
      - DuplicateInterface
      - DuplicateInterfacePrefix
      - EmptyImplements
      - ImplicitConstructorInvoker
      - MixinInnerClass
      - MixinSuperClass
      - InvalidMixinTarget
      - OverwriteModifiers
      - ShadowModifiers
      - InvalidConfigValue
      - InvalidInjectorMethodSignature
      - InvalidMemberReference
      - InvalidMixinPluginRegistration
      - InvalidMixinRegistration
      - InvalidInterfacePrefix
      - MissingUnique
      - CancellableInjectionUsage
      - AnnotationOutsideOfMixin
      - NonJavaMixin
      - UnusedMixin
      - ShadowFinalModification
      - ModifyVariableMayBeArgsOnly
      - AddedMixinMembersNamePattern
      - OverwriteAuthorRequired
      - PublicStaticMixinMember
      - ReferenceToMixin
      - SoftImplementOverrides
      - UnnecessaryQualifiedMemberReference
      - UnqualifiedMemberReference
      - UnresolvedConfigReference
      - MixinAnnotationTarget
      - UnresolvedMixinReference
      - UnusedShadowMethodPrefix
      - InconsistentLanguageLevel
      - ModuleWithTooManyClasses
      - NotNullFieldNotInitialized
      - NullableProblems
      - ReturnNull
      - UnsatisfiedRange
      - BigDecimalEquals
      - ComparisonOfShortAndChar
      - ConfusingFloatingPointLiteral
      - ConstantMathCall
      - FloatingPointEquality
      - OctalAndDecimalIntegersMixed
      - OverlyComplexArithmeticExpression
      - BadOddness
      - SuspiciousLiteralUnderscore
      - InsertLiteralUnderscores
      - JavaModuleNaming
      - ExceptionPackage
      - PackageWithTooManyClasses
      - PatternOverriddenByNonAnnotatedMethod
      - PatternNotApplicable
      - PatternValidation
      - ObjectEqualsCanBeEquality
      - IOStreamConstructor
      - MapReplaceableByEnumMap
      - SetReplaceableByEnumSet
      - StringEqualsEmptyString
      - StringBufferToStringInConcatenation
      - StringBufferMustHaveInitialCapacity
      - BulkFileAttributesRead
      - ArraysAsListWithZeroOrOneArgument
      - CallToSimpleGetterInClass
      - CallToSimpleSetterInClass
      - CollectionsMustHaveInitialCapacity
      - DynamicRegexReplaceableByCompiledPattern
      - ExplicitArgumentCanBeLambda
      - FieldMayBeStatic
      - KeySetIterationMayUseEntrySet
      - MethodMayBeStatic
      - StringReplaceableByStringBuffer
      - ObjectInstantiationInEqualsHashCode
      - LengthOneStringInIndexOf
      - LengthOneStringsInConcatenation
      - TailRecursion
      - RandomDoubleForRandomInteger
      - RuntimeExec
      - SystemExit
      - HardcodedFileSeparators
      - HardcodedLineSeparators
      - NativeMethods
      - UseOfProcessBuilder
      - UseOfSunClasses
      - UseOfAWTPeerClass
      - UseOfJDBCDriverClass
      - ClashingGetters
      - UnnecessaryQualifiedReference
      - ComparableImplementedButEqualsNotOverridden
      - MisspelledEquals
      - EqualsAndHashcode
      - InstanceofIncompatibleInterface
      - IteratorNextDoesNotThrowNoSuchElementException
      - ArrayEquality
      - JCenterRepository
      - ObjectToString
      - CastConflictsWithInstanceof
      - CastToIncompatibleInterface
      - ConstantAssertCondition
      - CovariantEquals
      - InnerClassReferencedViaSubclass
      - CompareToUsesNonFinalVariable
      - EqualsUsesNonFinalVariable
      - HashCodeUsesNonFinalVariable
      - NonShortCircuitBoolean
      - ObjectEquality
      - VariableNotUsedInsideIf
      - ResultOfObjectAllocationIgnored
      - StaticFieldReferenceOnSubclass
      - StaticCallOnSubclass
      - StringConcatenationInFormatCall
      - StringConcatenationInMessageFormatCall
      - SubtractionInCompareTo
      - SuspiciousArrayCast
      - ClassNewInstance
      - UseOfPropertiesAsHashtable
      - StringConcatenationMissingWhitespace
      - GrazieInspection
      - IdentifierGrammar
      - LanguageDetectionInspection
      - StructuralWrap
      - Style
      - SpellCheckingInspection
      - ValeProblem
      - QodanaSanity
      - RedundantModifiersUtilityClassLombok
      - RegExpAnonymousGroup
      - RegExpOctalEscape
      - RegExpRedundantEscape
      - RegExpSimplifiable
      - ChannelResource
      - IOResource
      - JDBCResource
      - JNDIResource
      - SocketResource
      - DriverManagerGetConnection
      - ClassLoaderInstantiation
      - PublicStaticArrayField
      - PublicStaticCollectionField
      - SystemProperties
      - JDBCPrepareStatementWithNonConstantString
      - RuntimeExecWithNonConstantString
      - JDBCExecuteWithNonConstantString
      - LoadLibraryWithNonConstantString
      - SystemSetSecurityManager
      - CustomClassloader
      - CustomSecurityManager
      - VulnerableLibrariesGlobal
      - ComparatorNotSerializable
      - ReadObjectAndWriteObjectPrivate
      - ReadResolveAndWriteReplaceProtected
      - SerializableStoresNonSerializable
      - SerialPersistentFieldsWithWrongSignature
      - ExternalizableWithSerializationMethods
      - ReadObjectInitialization
      - NonSerializableWithSerializationMethods
      - NonSerializableFieldInSerializableClass
      - NonSerializableObjectBoundToHttpSession
      - NonSerializableObjectPassedToObjectStream
      - SerializableWithUnconstructableAncestor
      - SerializableHasSerializationMethods
      - SerializableInnerClassWithNonSerializableOuterClass
      - SerializableInnerClassHasSerialVersionUIDField
      - TransientFieldInNonSerializableClass
      - TransientFieldNotInitialized
      - AwaitNotInLoop
      - AwaitWithoutCorrespondingSignal
      - NotifyCalledOnCondition
      - NakedNotify
      - NotifyWithoutCorrespondingWait
      - SignalWithoutCorrespondingAwait
      - ThreadLocalNotStaticFinal
      - SharedThreadLocalRandom
      - WaitCalledOnCondition
      - WaitNotInLoop
      - WaitOrAwaitWithoutTimeout
      - WaitNotifyNotInSynchronizedContext
      - WaitWithoutCorrespondingNotify
      - AccessToStaticFieldLockedOnInstance
      - ObjectNotify
      - ConditionSignal
      - ThreadPriority
      - SleepWhileHoldingLock
      - ThreadStartInConstruction
      - ThreadStopSuspendResume
      - ThreadYield
      - CallToNativeMethodWhileLocked
      - ExtendsThread
      - FieldAccessedSynchronizedAndUnsynchronized
      - SafeLock
      - MethodMayBeSynchronized
      - NestedSynchronizedStatement
      - PublicFieldAccessedInSynchronizedContext
      - AccessToNonThreadSafeStaticFieldFromInstance
      - SynchronizationOnStaticField
      - SynchronizeOnThis
      - SynchronizeOnLock
      - SynchronizedOnLiteralObject
      - UnconditionalWait
      - NonSynchronizedMethodOverridesSynchronizedMethod
      - VolatileArrayField
      - StringBufferReplaceableByString
      - RedundantExplicitChronoField
      - CastCanBeReplacedWithVariable
      - RedundantComparatorComparing
      - TrivialStringConcatenation
      - ConditionCoveredByFurtherCondition
      - DuplicateBranchesInSwitch
      - ExcessiveLambdaUsage
      - ExcessiveRangeCheck
      - ExplicitArrayFilling
      - RedundantCompareToJavaTime
      - ManualMinMaxCalculation
      - DuplicateExpressions
      - NonStrictComparisonCanBeEquality
      - ObviousNullCheck
      - OnlyOneElementUsed
      - SimplifyOptionalCallChains
      - RedundantCollectionOperation
      - RedundantCompareCall
      - RedundantFileCreation
      - RedundantClassCall
      - StringOperationCanBeSimplified
      - RedundantArrayCreation
      - RedundantLengthCheck
      - RedundantEscapeInRegexReplacement
      - RedundantStreamOptionalCall
      - RedundantTypeArguments
      - RedundantCast
      - RedundantUnmodifiable
      - ReplaceOnLiteralHasNoEffect
      - SimplifyCollector
      - SimplifyStreamApiCallChains
      - CastCanBeRemovedNarrowingVariableType
      - UnnecessaryStringEscape
      - UnnecessaryBreak
      - UnnecessaryContinue
      - UnnecessaryDefault
      - UnnecessaryReturn
      - UnnecessaryLabelOnBreakStatement
      - UnnecessaryLabelOnContinueStatement
      - IgnoreFileDuplicateEntry
      - PublicConstructorInNonPublicClass
      - AmbiguousFieldAccess
      - AnonymousClassVariableHidesContainingMethodVariable
      - AmbiguousMethodCall
      - InnerClassVariableHidesOuterClassVariable
      - LambdaParameterHidingMemberVariable
      - LocalVariableHidingMemberVariable
      - MethodOverridesInaccessibleMethodOfSuper
      - MethodOverridesStaticMethod
      - ParameterHidingMemberVariable
      - MethodOverloadsParentMethod
      - FieldHidesSuperclassField 
